# This file is automatically generated by ruby-ll. Manually changing this file
# is not recommended as any changes will be lost the next time this parser is
# re-generated.
require 'll/setup'

module Marvin
require 'ast'
class Parser < LL::Driver
  CONFIG = LL::DriverConfig.new

  CONFIG.terminals = [
    :$EOF, # 0
    :T_TYPE, # 1
    :T_CHAR, # 2
    :T_SPACE, # 3
    :T_DIGIT, # 4
    :T_BOOLOP, # 5
    :T_BOOLVAL, # 6
    :T_INTOP, # 7
    :T_LBRACKET, # 8
    :T_RBRACKET, # 9
    :T_DOLLAR, # 10
    :T_LPAREN, # 11
    :T_RPAREN, # 12
    :T_QUOTE, # 13
    :T_EQUALS, # 14
    :T_PRINT, # 15
    :T_WHILE, # 16
    :T_IF, # 17
  ].freeze

  CONFIG.rules = [
    [3, 0, 1, 10, 0, 1], # 0
    [3, 1, 1, 9, 0, 2, 1, 8], # 1
    [3, 2, 0, 2, 0, 3], # 2
    [3, 3, 2, 0], # 3
    [3, 4, 0, 1], # 4
  ].freeze

  CONFIG.table = [
    [-1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1], # 0
    [-1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1], # 1
    [3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3], # 2
    [-1, -1, -1, -1, -1, -1, -1, -1, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1], # 3
  ].freeze

  CONFIG.actions = [
    [:_rule_0, 2], # 0
    [:_rule_1, 3], # 1
    [:_rule_2, 2], # 2
    [:_rule_3, 0], # 3
    [:_rule_4, 1], # 4
  ].freeze

  def initialize(tokens)
    @tokens = tokens
  end

  def each_token
    @tokens.each do |token|
      yield [token.first, token.last]
    end

    yield [-1, -1]
  end

  def s(*args)
    return AST::Node.new(*args)
  end

  def _rule_0(val)
     s(:program, val[0]) 
  end

  def _rule_1(val)
     s(:block, val[1]) 
  end

  def _rule_2(val)
     s(:statement_list, val[1]) 
  end

  def _rule_3(val)
    val
  end

  def _rule_4(val)
     s(:block, ['boo']) 
  end
end
end
